## Import Data

In [2]:
conda install plotly-geo

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [41]:
conda install plotly

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [42]:
conda install geopandas

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [5]:
conda install geopandas=0.8.1

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import plotly
import plotly.express as px

In [2]:
url = "/Users/ivan/Documents/Davis/COURSES/4th Year/Spring 2021/STA160/Final/COVID_Cases_Restricted_Detailed_05112021_Part_1.parquet"

df1 = pd.read_parquet(url)

In [3]:
url2 = "/Users/ivan/Documents/Davis/COURSES/4th Year/Spring 2021/STA160/Final/COVID_Cases_Restricted_Detailed_05112021_Part_2.parquet"

df2 = pd.read_parquet(url2)

In [4]:
df1

,abdom_yn,abxchest_yn,acuterespdistress_yn,age_group,cdc_case_earliest_dt,cdc_report_dt,chills_yn,county_fips_code,cough_yn,current_status,...,onset_dt,pna_yn,pos_spec_dt,race_ethnicity_combined,res_county,res_state,runnose_yn,sex,sob_yn,sthroat_yn
0,Missing,Missing,Missing,10 - 19 Years,2021-02-06,2021-02-06,Missing,45001,Missing,Laboratory-confirmed case,...,None,Missing,None,Unknown,ABBEVILLE,SC,Missing,Female,Missing,Missing
1,Missing,Missing,Missing,10 - 19 Years,2021-01-28,2021-01-28,Missing,45001,Missing,Laboratory-confirmed case,...,None,Missing,None,Unknown,ABBEVILLE,SC,Missing,Female,Missing,Missing
2,Missing,Missing,Missing,10 - 19 Years,2021-01-19,2021-01-19,Missing,45001,Missing,Laboratory-confirmed case,...,None,Missing,None,Unknown,ABBEVILLE,SC,Missing,Female,Missing,Missing
3,Missing,Missing,Missing,10 - 19 Years,2021-01-07,2021-01-07,Missing,45001,Missing,Laboratory-confirmed case,...,None,Missing,None,Unknown,ABBEVILLE,SC,Missing,Female,Missing,Missing
4,Missing,Missing,Missing,10 - 19 Years,2020-07-20,2020-07-20,Missing,45001,Missing,Laboratory-confirmed case,...,None,Missing,None,Unknown,ABBEVILLE,SC,Missing,Female,Missing,Missing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12999995,Missing,Missing,Missing,40 - 49 Years,2020-07-22,2020-07-22,Missing,40109,Missing,Laboratory-confirmed case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing
12999996,Missing,Missing,Missing,40 - 49 Years,2021-04-02,2021-04-02,Missing,40109,Missing,Laboratory-confirmed case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing
12999997,Missing,Missing,Missing,40 - 49 Years,2020-10-30,2020-10-30,Missing,40109,Missing,Laboratory-confirmed case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing
12999998,Missing,Missing,Missing,40 - 49 Years,2020-09-18,2020-09-18,Missing,40109,Missing,Laboratory-confirmed case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing
12999999,Missing,Missing,Missing,40 - 49 Years,2021-03-08,2021-03-08,Missing,40109,Missing,Probable Case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing

In [5]:
df2

,abdom_yn,abxchest_yn,acuterespdistress_yn,age_group,cdc_case_earliest_dt,cdc_report_dt,chills_yn,county_fips_code,cough_yn,current_status,...,onset_dt,pna_yn,pos_spec_dt,race_ethnicity_combined,res_county,res_state,runnose_yn,sex,sob_yn,sthroat_yn
0,Missing,Missing,Missing,40 - 49 Years,2020-10-02,2020-10-02,Missing,40109,Missing,Laboratory-confirmed case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing
1,Missing,Missing,Missing,40 - 49 Years,2020-11-10,2020-11-10,Missing,40109,Missing,Probable Case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing
2,Missing,Missing,Missing,40 - 49 Years,2021-01-17,2021-01-17,Missing,40109,Missing,Probable Case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing
3,Missing,Missing,Missing,40 - 49 Years,2020-11-27,2020-11-27,Missing,40109,Missing,Probable Case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing
4,Missing,Missing,Missing,40 - 49 Years,2020-10-23,2020-10-23,Missing,40109,Missing,Laboratory-confirmed case,...,None,Missing,None,"White, Non-Hispanic",OKLAHOMA,OK,Missing,Female,Missing,Missing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12120917,Missing,Missing,Missing,20 - 29 Years,2020-12-01,2020-12-01,Missing,46137,Missing,Laboratory-confirmed case,...,None,Missing,None,"American Indian/Alaska Native, Non-Hispanic",ZIEBACH,SD,Missing,Female,Missing,Missing
12120918,Missing,Missing,Missing,20 - 29 Years,2020-10-20,2021-01-06,Missing,46137,Missing,Laboratory-confirmed case,...,2020-10-20,Missing,None,"American Indian/Alaska Native, Non-Hispanic",ZIEBACH,SD,Missing,Female,Missing,Missing
12120919,Missing,Missing,Missing,20 - 29 Years,2020-07-27,2020-12-01,Missing,46137,Missing,Laboratory-confirmed case,...,2020-07-27,Missing,None,"American Indian/Alaska Native, Non-Hispanic",ZIEBACH,SD,Missing,Female,Missing,Missing
12120920,Missing,Missing,Missing,20 - 29 Years,2020-07-25,2020-12-01,Missing,46137,Missing,Laboratory-confirmed case,...,2020-07-25,Missing,None,"American Indian/Alaska Native, Non-Hispanic",ZIEBACH,SD,Missing,Female,Missing,Missing
12120921,Missing,Missing,Missing,20 - 29 Years,2020-11-06,2021-01-06,Missing,46137,Missing,Laboratory-confirmed case,...,2020-11-06,Missing,None,"American Indian/Alaska Native, Non-Hispanic",ZIEBACH,SD,Missing,Female,Missing,Missing

In [6]:
df = pd.concat([df1, df2], ignore_index=True)

In [7]:
df.dtypes

abdom_yn                   object
abxchest_yn                object
acuterespdistress_yn       object
age_group                  object
cdc_case_earliest_dt       object
cdc_report_dt              object
chills_yn                  object
county_fips_code           object
cough_yn                   object
current_status             object
death_yn                   object
diarrhea_yn                object
fever_yn                   object
sfever_yn                  object
hc_work_yn                 object
headache_yn                object
hosp_yn                    object
icu_yn                     object
mechvent_yn                object
medcond_yn                 object
myalgia_yn                 object
nauseavomit_yn             object
onset_dt                   object
pna_yn                     object
pos_spec_dt                object
race_ethnicity_combined    object
res_county                 object
res_state                  object
runnose_yn                 object
sex                        object
sob_yn                     object
sthroat_yn                 object
dtype: object

### Restricted Data Specifications

A restricted access, detailed version of line-listed dataset of all COVID-19 cases reported to CDC is available. The dataset is to be made available for limited use upon completion of the RIDURA. COVID-19 data may differ substantially in the variables reported and in completeness by state. Some data are suppressed to protect patient privacy by coding as NA (see Data Suppression below). The restricted access data set includes the following variables:

- The earlier of the Clinical Date: Cdc_case_earliest_dt uses the best available date from both cdc_received_dt and cdc_clinical_obs_dt and is an option to end-users who need a date variable with optimized completeness. The logic of cdc_case_earliest_dt is to use the non-null date of one variable when the other is null and to use the earliest valid date when both dates are available.
- Initial report date of case to CDC (Deprecated, use the earlier of the Clinical Date): This date was populated using the date at which a case record was first submitted to the database. If missing, then the report date entered on the case report form was used. If missing, then the date at which the case first appeared in the database was used.
- Date of first positive specimen collection
- Symptom onset date, if symptomatic // 'Date when symptom first appears'
- Case status
- Sex
- Age group (0-9, 10-19, 20-29, 30-39, 40-49, 50-59, 60-69, 70-79, 80+ years)
- Race and ethnicity (combined)
- State of residence
- County of residence
- County FIPS code
- Healthcare worker status
- Pneumonia present
- Acute respiratory distress syndrome (ARDS) present
- Abnormal chest x-ray (CXR) present
- Hospitalization status
- ICU admission status
- Mechanical ventilation (MV)/intubation status
- Death status
- Presence of each of the following symptoms: fever, subjective fever, chills, myalgia, rhinorrhea, sore throat, cough, shortness of breath, nausea/vomiting, headache, abdominal pain, diarrhea
- Presence of underlying comorbidity or disease

In [8]:
max(df["cdc_case_earliest_dt"])

datetime.date(2021, 4, 26)

In [9]:
min(df["cdc_case_earliest_dt"])

datetime.date(2020, 1, 1)

In [10]:
min(df2["cdc_case_earliest_dt"])

datetime.date(2020, 1, 1)

In [11]:
max(df2["cdc_case_earliest_dt"])

datetime.date(2021, 4, 26)

### Overview

- Data Cleaning 
    - observe outliers 
    - show which are the outliers
- EDA
    - Bar plot 
    - Heatmaps 
- Models
    - K - means 
    - NN
    - H Clustering
        - Obtain more features:
            - economic data
            - political leaning 
            - pm2.5

Requesting air pollution data from USEPA (info on parameters: https://aqs.epa.gov/aqsweb/documents/data_api.html)

#### *References:*

- https://github.com/wxwx1993/PM_COVID
-

## Data Cleaning

We notice that null values appears to be in the forms of 'Missing', 'None', 'Unknown'

We will check how many null values appear in each of the columns

### Cleaning Combined Dataframe

In [12]:
#cleaning states with "NA" and "Missing"
df = df[df.res_state != "NA"]
df = df[df.res_state != "Missing"]

In [13]:
df.shape

(25118783, 32)

In [14]:
df.isna().sum()

abdom_yn                          0
abxchest_yn                       0
acuterespdistress_yn              0
age_group                         0
cdc_case_earliest_dt              0
cdc_report_dt               2262777
chills_yn                         0
county_fips_code             756648
cough_yn                          0
current_status                    0
death_yn                          0
diarrhea_yn                       0
fever_yn                          0
sfever_yn                         0
hc_work_yn                        0
headache_yn                       0
hosp_yn                           0
icu_yn                            0
mechvent_yn                       0
medcond_yn                        0
myalgia_yn                        0
nauseavomit_yn                    0
onset_dt                   13426491
pna_yn                            0
pos_spec_dt                18312764
race_ethnicity_combined           0
res_county                        0
res_state                         0
runnose_yn                        0
sex                               0
sob_yn                            0
sthroat_yn                        0
dtype: int64

Shows the amount of null/na values per column

In [15]:
df = df.drop(['onset_dt', 'pos_spec_dt', 'cdc_report_dt'], axis = 1)

In [16]:
df.isna().sum()

abdom_yn                        0
abxchest_yn                     0
acuterespdistress_yn            0
age_group                       0
cdc_case_earliest_dt            0
chills_yn                       0
county_fips_code           756648
cough_yn                        0
current_status                  0
death_yn                        0
diarrhea_yn                     0
fever_yn                        0
sfever_yn                       0
hc_work_yn                      0
headache_yn                     0
hosp_yn                         0
icu_yn                          0
mechvent_yn                     0
medcond_yn                      0
myalgia_yn                      0
nauseavomit_yn                  0
pna_yn                          0
race_ethnicity_combined         0
res_county                      0
res_state                       0
runnose_yn                      0
sex                             0
sob_yn                          0
sthroat_yn                      0
dtype: int64

We find that there is 756648 missing county_fips_code values

In [17]:
df = df.dropna(axis=0)
df.isna().sum()

abdom_yn                   0
abxchest_yn                0
acuterespdistress_yn       0
age_group                  0
cdc_case_earliest_dt       0
chills_yn                  0
county_fips_code           0
cough_yn                   0
current_status             0
death_yn                   0
diarrhea_yn                0
fever_yn                   0
sfever_yn                  0
hc_work_yn                 0
headache_yn                0
hosp_yn                    0
icu_yn                     0
mechvent_yn                0
medcond_yn                 0
myalgia_yn                 0
nauseavomit_yn             0
pna_yn                     0
race_ethnicity_combined    0
res_county                 0
res_state                  0
runnose_yn                 0
sex                        0
sob_yn                     0
sthroat_yn                 0
dtype: int64

#### Density Map of Death Proportions

Visualizing counties with the highest death proportion

In [18]:
#seeing if death_yn has unknown values
df.death_yn.value_counts()

No         12425838
Missing     8911369
Unknown     2573040
Yes          451888
Name: death_yn, dtype: int64

In [19]:
#dropping values with unknown death values
df_death = df.loc[(df['death_yn'] == "No") | (df['death_yn'] == "Yes")]
df_death

,abdom_yn,abxchest_yn,acuterespdistress_yn,age_group,cdc_case_earliest_dt,chills_yn,county_fips_code,cough_yn,current_status,death_yn,...,myalgia_yn,nauseavomit_yn,pna_yn,race_ethnicity_combined,res_county,res_state,runnose_yn,sex,sob_yn,sthroat_yn
16,Missing,Missing,Missing,10 - 19 Years,2021-01-13,Missing,45001,Missing,Laboratory-confirmed case,No,...,Missing,Missing,Missing,Unknown,ABBEVILLE,SC,Missing,Female,Missing,Missing
58,Missing,Missing,Missing,10 - 19 Years,2021-01-11,Missing,45001,Missing,Laboratory-confirmed case,No,...,Missing,Missing,Missing,Hispanic/Latino,ABBEVILLE,SC,Missing,Male,Missing,Missing
59,Missing,Missing,Missing,10 - 19 Years,2020-07-20,Missing,45001,Missing,Laboratory-confirmed case,No,...,Missing,Missing,Missing,Hispanic/Latino,ABBEVILLE,SC,Missing,Male,Missing,Missing
60,Missing,Missing,Missing,10 - 19 Years,2021-01-13,Missing,45001,Missing,Laboratory-confirmed case,No,...,Missing,Missing,Missing,Hispanic/Latino,ABBEVILLE,SC,Missing,Male,Missing,Missing
62,Missing,Missing,Missing,10 - 19 Years,2021-03-22,Missing,45001,Missing,Laboratory-confirmed case,No,...,Missing,Missing,Missing,Hispanic/Latino,ABBEVILLE,SC,Missing,Male,Missing,Missing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25120871,Missing,Missing,Missing,70 - 79 Years,2020-05-31,Missing,04027,Missing,Laboratory-confirmed case,No,...,Missing,Missing,Missing,Hispanic/Latino,YUMA,AZ,Missing,Female,Missing,Missing
25120885,Missing,Missing,Missing,30 - 39 Years,2020-04-23,Missing,08125,Missing,Laboratory-confirmed case,No,...,Missing,Missing,Missing,Hispanic/Latino,YUMA,CO,Missing,Female,Missing,Missing
25120890,Missing,Missing,Missing,30 - 39 Years,2020-07-25,Missing,08125,Missing,Laboratory-confirmed case,No,...,Missing,Missing,Missing,Hispanic/Latino,YUMA,CO,Missing,Female,Missing,Missing
25120901,Missing,Missing,Missing,70 - 79 Years,2020-09-06,Missing,08125,Missing,Laboratory-confirmed case,No,...,Missing,Missing,Missing,Unknown,YUMA,CO,Missing,Male,Missing,Missing
25120903,Missing,Missing,Missing,70 - 79 Years,2021-01-13,Missing,08125,Missing,Laboratory-confirmed case,Yes,...,Missing,Missing,Missing,Unknown,YUMA,CO,Missing,Male,Missing,Missing

In [20]:
df_death = df_death[["res_state", "county_fips_code", "death_yn", "abdom_yn"]]
df_death_counts = df_death.groupby(["res_state", "county_fips_code","death_yn"]).count()

In [21]:
df_death_counts = df_death_counts.rename(columns={"abdom_yn": "death_count"})

In [22]:
df_death_counts = df_death_counts.reset_index()

In [23]:
df_death_counts

     res_state county_fips_code death_yn  death_count
0           AK            02013       No           35
1           AK            02016       No           17
2           AK            02016      Yes            1
3           AK            02020       No         2119
4           AK            02020      Yes          175
...        ...              ...      ...          ...
5173        WY            56039       No           95
5174        WY            56039      Yes            2
5175        WY            56041       No           72
5176        WY            56043       No           17
5177        WY            56043      Yes            5

[5178 rows x 4 columns]

In [24]:
df_known_patient_fips = df_death_counts.groupby(["res_state", "county_fips_code"]).sum()
df_known_patient_fips = df_known_patient_fips.rename(columns={"death_count": "patient_total"})
df_known_patient_fips = df_known_patient_fips.reset_index()
df_known_patient_fips

     res_state county_fips_code  patient_total
0           AK            02013             35
1           AK            02016             18
2           AK            02020           2294
3           AK            02050            194
4           AK            02060             27
...        ...              ...            ...
2745        WY            56035              4
2746        WY            56037             56
2747        WY            56039             97
2748        WY            56041             72
2749        WY            56043             22

[2750 rows x 3 columns]

In [25]:
df_death_counts_yes = df_death_counts[df_death_counts.death_yn == 'Yes']

In [26]:
df_death_counts_yes

     res_state county_fips_code death_yn  death_count
2           AK            02016      Yes            1
4           AK            02020      Yes          175
6           AK            02050      Yes           21
10          AK            02070      Yes            2
12          AK            02090      Yes           36
...        ...              ...      ...          ...
5163        WY            56019      Yes            1
5165        WY            56021      Yes            2
5168        WY            56025      Yes            1
5174        WY            56039      Yes            2
5177        WY            56043      Yes            5

[2515 rows x 4 columns]

In [27]:
df_death_counts_yes = df_death_counts_yes.merge(df_known_patient_fips, how='left')
df_death_counts_yes

     res_state county_fips_code death_yn  death_count  patient_total
0           AK            02016      Yes            1             18
1           AK            02020      Yes          175           2294
2           AK            02050      Yes           21            194
3           AK            02070      Yes            2            104
4           AK            02090      Yes           36            753
...        ...              ...      ...          ...            ...
2510        WY            56019      Yes            1             17
2511        WY            56021      Yes            2            148
2512        WY            56025      Yes            1             46
2513        WY            56039      Yes            2             97
2514        WY            56043      Yes            5             22

[2515 rows x 5 columns]

In [28]:
df_death_counts_yes['death_prop'] = df_death_counts_yes['death_count']/df_death_counts_yes['patient_total']
df_death_counts_yes

,res_state,county_fips_code,death_yn,death_count,patient_total,death_prop
0,AK,02016,Yes,1,18,0.055556
1,AK,02020,Yes,175,2294,0.076286
2,AK,02050,Yes,21,194,0.108247
3,AK,02070,Yes,2,104,0.019231
4,AK,02090,Yes,36,753,0.047809
...,...,...,...,...,...,...
2510,WY,56019,Yes,1,17,0.058824
2511,WY,56021,Yes,2,148,0.013514
2512,WY,56025,Yes,1,46,0.021739
2513,WY,56039,Yes,2,97,0.020619
2514,WY,56043,Yes,5,22,0.227273

In [29]:
conda install -c plotly plotly-geo

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [37]:
pip install geopandas==0.3.0

Collecting geopandas==0.3.0
  Downloading geopandas-0.3.0-py2.py3-none-any.whl (888 kB)
     |████████████████████████████████| 888 kB 3.4 MB/s eta 0:00:01
Requirement already satisfied: fiona in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from geopandas==0.3.0) (1.8.13.post1)
Requirement already satisfied: shapely in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from geopandas==0.3.0) (1.7.1)
Requirement already satisfied: pandas in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from geopandas==0.3.0) (1.2.4)
Requirement already satisfied: pyproj in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from geopandas==0.3.0) (2.6.1.post1)
Collecting descartes
  Using cached descartes-1.1.0-py3-none-any.whl (5.8 kB)
Requirement already satisfied: matplotlib in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from descartes->geopandas==0.3.0) (3.3.4)
Requirement already satisfied: attrs>=17 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from fiona->geopandas==0.3.0) (21.2.0)
Requirement already satisfied: click<8,>=4.0 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from fiona->geopandas==0.3.0) (7.1.2)
Requirement already satisfied: cligj>=0.5 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from fiona->geopandas==0.3.0) (0.7.2)
Requirement already satisfied: click-plugins>=1.0 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from fiona->geopandas==0.3.0) (1.1.1)
Requirement already satisfied: six>=1.7 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from fiona->geopandas==0.3.0) (1.15.0)
Requirement already satisfied: munch in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from fiona->geopandas==0.3.0) (2.5.0)
Requirement already satisfied: cycler>=0.10 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from matplotlib->descartes->geopandas==0.3.0) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from matplotlib->descartes->geopandas==0.3.0) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from matplotlib->descartes->geopandas==0.3.0) (8.2.0)
Requirement already satisfied: numpy>=1.15 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from matplotlib->descartes->geopandas==0.3.0) (1.20.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from matplotlib->descartes->geopandas==0.3.0) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from matplotlib->descartes->geopandas==0.3.0) (1.3.1)
Requirement already satisfied: pytz>=2017.3 in /Users/ivan/opt/anaconda3/envs/my_env/lib/python3.7/site-packages (from pandas->geopandas==0.3.0) (2021.1)
Installing collected packages: descartes, geopandas
  Attempting uninstall: geopandas
    Found existing installation: geopandas 0.8.1
    Uninstalling geopandas-0.8.1:
      Successfully uninstalled geopandas-0.8.1
Successfully installed descartes-1.1.0 geopandas-0.3.0
Note: you may need to restart the kernel to use updated packages.

In [38]:
pip install pyshp==1.2.10

Collecting pyshp==1.2.10
  Downloading pyshp-1.2.10.tar.gz (176 kB)
     |████████████████████████████████| 176 kB 3.9 MB/s eta 0:00:01
Building wheels for collected packages: pyshp
  Building wheel for pyshp (setup.py) ... done
  Created wheel for pyshp: filename=pyshp-1.2.10-py3-none-any.whl size=20467 sha256=39cc11fb05c6aecd5997d9e7bfe31b95e89ad3f5734730d6434711afa08d7bd0
  Stored in directory: /Users/ivan/Library/Caches/pip/wheels/aa/cb/ed/c4af42e7718157f9a76dea841c585e0577742ffed5a5b17d32
Successfully built pyshp
Installing collected packages: pyshp
  Attempting uninstall: pyshp
    Found existing installation: pyshp 2.1.3
    Uninstalling pyshp-2.1.3:
      Successfully uninstalled pyshp-2.1.3
Successfully installed pyshp-1.2.10
Note: you may need to restart the kernel to use updated packages.

In [39]:
pip install shapely==1.6.3

Collecting shapely==1.6.3
  Downloading Shapely-1.6.3.tar.gz (223 kB)
     |████████████████████████████████| 223 kB 3.4 MB/s eta 0:00:01
Building wheels for collected packages: shapely
  Building wheel for shapely (setup.py) ... done
  Created wheel for shapely: filename=Shapely-1.6.3-cp37-cp37m-macosx_10_9_x86_64.whl size=216532 sha256=8be33302b00819d652036d64ec4a4d17f5bf31b8b0bd66920789dc2ee189fd91
  Stored in directory: /Users/ivan/Library/Caches/pip/wheels/89/9f/1e/de1b1c770313c6a9838cc9c4da4c59f5b2db78b34078d29d01
Successfully built shapely
Installing collected packages: shapely
  Attempting uninstall: shapely
    Found existing installation: Shapely 1.7.1
    Uninstalling Shapely-1.7.1:
      Successfully uninstalled Shapely-1.7.1
Successfully installed shapely-1.6.3
Note: you may need to restart the kernel to use updated packages.

In [4]:
colorscale = ["#f7fbff","#ebf3fb","#deebf7","#d2e3f3","#c6dbef","#b3d2e9","#9ecae1",
              "#85bcdb","#6baed6","#57a0ce","#4292c6","#3082be","#2171b5","#1361a9",
              "#08519c","#0b4083","#08306b"]
endpts = list(np.linspace(1, 12, len(colorscale) - 1))
fips = df_death_counts_yes['county_fips_code'].tolist()
values = df_death_counts_yes['death_prop'].tolist()

fig = px.choropleth(
    fips=fips, values=values,
    binning_endpoints=endpts,
    colorscale=colorscale,
    show_state_data=False,
    show_hover=True, centroid_marker={'opacity': 0},
    asp=2.9, title='USA by COVID Death Percentage',
    legend_title='Death Percentage'
)

fig.layout.template = None
fig.show()

NameError: name 'df_death_counts_yes' is not defined

Drop irrelevant date values then, find better way to classify NA values encode all the other variables into 0s and 1s

#df = df.replace(['Missing','Unknown','None'], pd.NA) #this approach doesnt work

In [ ]:
#df['age_group'].value_counts()

In [ ]:
#df['current_status'].value_counts()

In [ ]:
#df['race_ethnicity_combined'].value_counts()

In [ ]:
import seaborn as sns
sns.set_theme(style="darkgrid")

ax = sns.countplot(y="age_group", data=df)

In [ ]:
#res_county, death_yn, age_group, race_ethnicity_combined

In [ ]:
g = sns.catplot(y="race_ethnicity_combined", hue="death_yn", col="age_group",

                data=df, kind="count", height=4, aspect=.7);

The plots show the amount of deaths per race/ethnicity per age group. We find that in this data set we mostly have missing and patients who survived the vaccine. It does appear in the 60-69 year group that we find a greator amount of deaths

## Models

- Models
    - K - means 
    - NN
    - H Clustering
        - Obtain more features:
            - economic data
            - political leaning 
            - pm2.5 
            

Create plot showing pm2.5 trend for each county over time range of dataset
- possible could do california to begin with 
- goal to show air pollution of the course of covid

Create plot showing pm2.5 averaged overtime with covid cases overtime
- could also show other features descibed above


Create a for-loop

**pm2.5 CALIFORNIA DATA**

Requesting air pollution data from USEPA (info on parameters: https://aqs.epa.gov/aqsweb/documents/data_api.html)

Parameters Info: https://www.epa.gov/aqs/aqs-code-list

In [ ]:
ca_c = "https://aqs.epa.gov/data/api/list/countiesByState?email=test@aqs.api&key=test&state=06"
response_json = requests.get(ca_c).json()
content = json.dumps(response_json, indent = 4, sort_keys=True)

In [ ]:
df_ca_county = pd.DataFrame(response_json["Data"])

In [ ]:
df_ca_county.head()

In [ ]:
county_num = df_ca_county['code']

county_num[0]

url2 = 'https://aqs.epa.gov/data/api/dailyData/byCounty?email=test@aqs.api&key=test&param=88101&bdate=20210101&edate=20210428&state=06&county=' + county_num[0]
response_json = requests.get(url2).json()
content = json.dumps(response_json, indent = 4, sort_keys=True)

In [ ]:
county_num[0]

In [ ]:
import requests
import json

url_cal = 'https://aqs.epa.gov/data/api/dailyData/byState?email=igyang@ucdavis.edu&key=orangefrog71&param=88502&bdate=20210101&edate=20210426&state=06'
response_json = requests.get(url_cal).json()
content = json.dumps(response_json, indent = 4, sort_keys=True)

In [ ]:
lst_pm_cal = response_json['Data']

In [ ]:
len(lst_pm_cal)

In [ ]:
lst_pm_cal[0]

In [ ]:
df_pm_cal = pd.DataFrame(lst_pm_cal)

In [ ]:
df_pm_cal.head()

In [ ]:
df_pm_cal.columns

In [ ]:
df_pm_cal['city'].value_counts()

**COUNTY POLITICAL DATA**

- https://www.sos.ca.gov/elections/report-registration/ror-odd-year-2021

**COUNTY ECONOMIC DATA**
- median income 
- house prices

**COUNTY POPULATION DATA**

https://www.census.gov/programs-surveys/popest/technical-documentation/research/evaluation-estimates/2020-evaluation-estimates/2010s-counties-total.html

In [ ]:
df_pop = pd.read_csv('/Users/vishnu/Documents/STA160/finalproj/datasets/co-est2020-alldata.csv', engine='python')

In [ ]:
df_pop.head()

In [ ]:
df_pop.dtypes

In [ ]:
df_pop.columns

In [ ]:
(df_pop.dtypes).value_counts()

Could take average of pop estimate over particular years

In [ ]:
df_pop = df_pop[["STATE","COUNTY","STNAME", "CTYNAME", "POPESTIMATE2020"]]


df_state_pop = df_pop[df_pop["COUNTY"] == 0]
df_state_pop = df_state_pop.drop(columns=["COUNTY", "CTYNAME"])

df_county_pop = df_pop[df_pop["COUNTY"] != 0]

In [ ]:
df_state_pop.head()

In [ ]:
df_county_pop.head()

**COUNTY COVID DATA**

Look on New York Time or John Hopkins Data - per county over time 

Aiming to generate alot of time series type plots